
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SectionLayout from "./_layouts/SectionLayout";
import { ToastContainer } from "react-toastify";
import QueryProvider from "@/tan-stack-redux/QueryProvider";
import HeaderLayout from "./_layouts/HeaderLayout";
import Header from "./_components/header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NoteBook",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider >
          <HeaderLayout>
            <Header />
          </HeaderLayout>
          <SectionLayout>
            {children}
            <ToastContainer position="top-center" />
          </SectionLayout>
        </QueryProvider >
      </body>
    </html>
  );
}
